apiVersion: arogproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: strimzi
spec:
  project: default
  source:
    chart: strimzi-kafka-operator
    repoURL: https://strimzi.io/charts
    targetRevision: 0.31.1
    helm:
      releaseName: strimzi
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi
